### ISSUE TITLE
Correcao metas de usabilidade

### ISSUE THREAD

**Issue by igorpenhaa** [Interacao-Humano-Computador/2023.1-BancoCentral#137]
Explicar como seria aplicado no projeto, mostrar algo no site que determinada meta deveria ser aplicado, algo como essa explicação, mas usando os conceitos das metas de usabilidade

![image](https://github.com/Interacao-Humano-Computador/2023.1-BancoCentral/assets/97994511/7e7aec96-de23-46c7-8321-af6baf7fc036)

**Comment by larigs** [comment]
Criei outra issue antes de ver essa, dá uma olhada na descrição, fiz baseada no que o prof falou
